In [3]:
import torch
import numpy as np

In [5]:
x = torch.Tensor([[1,2],[3,4]])
x = torch.from_numpy(np.array([[1,2],[3,4]]))
x

tensor([[1, 2],
        [3, 4]])

넘파이의 배열인 ndarray와 같은 개념입니다. 추가로 텐서간 연산에 따른 그래프와 경사도를 저장할 수 있습니다. 
파이토치는 텐서를 통해 값을 저장하고 그 값들에 대해 연산을 수행할 수 있는 함수를 제공합니다.

In [7]:
y = np.array([[1,2],[3,4]])
y

array([[1, 2],
       [3, 4]])

파이토치는 자동으로 미분 및 역전파를 수행하는 autograd기능을 가진다.
텐서들 간에 연산을 수행할 때마다 동적으로 연산그래프를 생성, 연산의 결과물이 어떤 텐서로부터 어떤 연산을 통해 왔는지 추적.

최종적으로 나온 스칼라에 역전파 알고리즘을 통해 미분을 수행하도록 했을 때, 각 텐서는 자기자신의 자식노드에 해당하는 텐서와 연산을 자동으로 찾아 계속해서 역전파 알고리즘을 수행할 수 있도록 한다.

In [10]:
x1 = torch.FloatTensor(2,2)
y1 = torch.FloatTensor(2,2)
y1.requires_grad_(True)

z = (x1+y1)+torch.FloatTensor(2,2)
z

tensor([[0.0000e+00, 0.0000e+00],
        [5.4718e+22, 1.7282e-04]], grad_fn=<AddBackward0>)

autograd는 PyTorch에서 핵심적인 기능을 담당하는 하부 패키지이다. autograd는 텐서의 연산에 대해 자동으로 미분값을 구해주는 기능을 한다. 텐서 자료를 생성할 때, requires_grad인수를 True로 설정하거나 .requires_grad_(True)를 실행하면 그 텐서에 행해지는 모든 연산에 대한 미분값을 계산한다. 계산을 멈추고 싶으면 .detach()함수를 이용하면 된다.

In [11]:
x2 = torch.FloatTensor(2,2)
y2 = torch.FloatTensor(2,2)
y.requires_grad_(True)

with torch.no_grad():
    z1 = (x2+y2) + torch.FloatTensor(2,2)
z1

tensor([[8.4078e-45, 1.4433e-43],
        [5.4718e+22, 1.7282e-04]])

In [ ]:
파이토치로 1차원 벡터를 만들어 봅시다.

In [12]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)
print(t.dim())
print(t.shape)
print(t.size())


tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])


In [13]:
print(t[0], t[1], t[-1])  # 인덱스로 접근
print(t[2:5], t[4:-1])    # 슬라이싱
print(t[:2], t[3:])       # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [14]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [15]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [16]:
print(t[:,1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져옴
print(t[:,1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [17]:
print(t[:,:-1]) # 맨 마지막 차원을 제외하고 다 가져오는 경우

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [18]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2) # 크기가 동일한 텐서간의 덧셈연산

tensor([[5., 5.]])


In [19]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3]) #pytorch broadcasting [3] > [3,3]
print(m1+m2)

tensor([[4., 5.]])


In [21]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1+m2) # 벡터간 연산에서 브로드캐스팅이 적용되는 경우

tensor([[4., 5.],
        [5., 6.]])
