In [1]:
import torch
import numpy as np

In [2]:
x = torch.Tensor([[1,2],[3,4]])
x = torch.from_numpy(np.array([[1,2],[3,4]]))
x

tensor([[1, 2],
        [3, 4]])

넘파이의 배열인 ndarray와 같은 개념입니다. 추가로 텐서간 연산에 따른 그래프와 경사도를 저장할 수 있습니다. 
파이토치는 텐서를 통해 값을 저장하고 그 값들에 대해 연산을 수행할 수 있는 함수를 제공합니다.

In [3]:
y = np.array([[1,2],[3,4]])
y

array([[1, 2],
       [3, 4]])

파이토치는 자동으로 미분 및 역전파를 수행하는 autograd기능을 가진다.
텐서들 간에 연산을 수행할 때마다 동적으로 연산그래프를 생성, 연산의 결과물이 어떤 텐서로부터 어떤 연산을 통해 왔는지 추적.

최종적으로 나온 스칼라에 역전파 알고리즘을 통해 미분을 수행하도록 했을 때, 각 텐서는 자기자신의 자식노드에 해당하는 텐서와 연산을 자동으로 찾아 계속해서 역전파 알고리즘을 수행할 수 있도록 한다.

In [4]:
x1 = torch.FloatTensor(2,2)
y1 = torch.FloatTensor(2,2)
y1.requires_grad_(True)

z = (x1+y1)+torch.FloatTensor(2,2)
z

tensor([[1.5414e-44, 0.0000e+00],
        [1.4013e-45, 2.3511e-38]], grad_fn=<AddBackward0>)

autograd는 PyTorch에서 핵심적인 기능을 담당하는 하부 패키지이다. autograd는 텐서의 연산에 대해 자동으로 미분값을 구해주는 기능을 한다. 텐서 자료를 생성할 때, requires_grad인수를 True로 설정하거나 .requires_grad_(True)를 실행하면 그 텐서에 행해지는 모든 연산에 대한 미분값을 계산한다. 계산을 멈추고 싶으면 .detach()함수를 이용하면 된다.

In [5]:
x2 = torch.FloatTensor(2,2)
y2 = torch.FloatTensor(2,2)
y2.requires_grad_(True)

with torch.no_grad():
    z1 = (x2+y2) + torch.FloatTensor(2,2)
z1

tensor([[1.5414e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])

파이토치로 1차원 벡터를 만들어 봅시다.

In [6]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)
print(t.dim())
print(t.shape)
print(t.size())


tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])


In [7]:
print(t[0], t[1], t[-1])  # 인덱스로 접근
print(t[2:5], t[4:-1])    # 슬라이싱
print(t[:2], t[3:])       # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [8]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [9]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [10]:
print(t[:,1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져옴
print(t[:,1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [11]:
print(t[:,:-1]) # 맨 마지막 차원을 제외하고 다 가져오는 경우

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [12]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2) # 크기가 동일한 텐서간의 덧셈연산

tensor([[5., 5.]])


In [13]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3]) #pytorch broadcasting [3] > [3,3]
print(m1+m2)

tensor([[4., 5.]])


In [14]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1+m2) # 벡터간 연산에서 브로드캐스팅이 적용되는 경우

tensor([[4., 5.],
        [5., 6.]])


In [15]:
# 행렬 곱셈과 곱셈의 차이
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1:', m1.shape)
print('Shape of Matrix 2:', m2.shape)
print(m1.matmul(m2))
print(m1*m2)
print(m1.mul(m2)) # element-wise

Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix 2: torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [16]:
t = torch.FloatTensor([1,2])
print(t.mean())
t1 = torch.FloatTensor([[1,2],[3,4]])
print(t1.mean())

tensor(1.5000)
tensor(2.5000)


In [17]:
print(t1.mean(dim=0))
# t.mean(dim=0)은 입력에서 첫번째 차원을 제거한다. (1과 3의평균 2, 2와 4의 평균 3)
mean1 = t1.mean(dim=0) # 행제거
print(mean1.shape)

mean2 = t1.mean(dim=1) # 열제거
print(mean2)
print(mean2.shape)


tensor([2., 3.])
torch.Size([2])
tensor([1.5000, 3.5000])
torch.Size([2])


In [18]:
print(t1.sum())
print(t1.sum(dim=0))
print(t1.sum(dim=1))
print(t1.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [19]:
print(t1.max()) # 원소 중 최대값
print(t1.max(dim=0)) # 첫번째 차원 제거
print(t1.max(dim=1))
print(t1.max(dim=-1))

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [20]:
# 두개를 함께 리턴받는 것이 아니라 max또는 argmax만 리턴받고 싶다면 리턴값에 인덱스를 부여

print('Max : ', t1.max(dim=0)[0])
print('Argmax : ', t1.max(dim=0)[1])

Max :  tensor([3., 4.])
Argmax :  tensor([1, 1])


인플레이스 연산 
명령어 뒤에 '_'를 붙이면 자기자신의 값을 바꾸는 인플레이스 명령이 된다. 인플레이스 명령은 연산 결과를 반환하면서 동시에
자기자신의 데이터를 고친다.

In [21]:
x = torch.arange(0,5)
z = torch.arange(1,6)

print(x)
print(x.add_(z))
print(x)

tensor([0, 1, 2, 3, 4])
tensor([1, 3, 5, 7, 9])
tensor([1, 3, 5, 7, 9])


View - 원소의 수를 유지하면서 텐서의 크기 변경
- 파이토치 텐서의 뷰는 넘파이에서의 리쉐이프와 같은 역할 (텐서의 크기 변경)
- view는 기본적으로 변경 전과 변경 후의 텐서 안의 원소의 개수가 유지되어야 함

In [22]:
t = np.array([[[0,1,2],
                [3,4,5]],
              [[6,7,8],
                [9,10,11]]])
ft = torch.FloatTensor(t)

In [23]:
print(ft.shape)

torch.Size([2, 2, 3])


In [24]:
# 3차원 > 2차원 텐서로 변경

print(ft.view([-1, 3])) #  (?,3)size의 2차원 텐서 생성
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [25]:
# (2*2*3) = (?*1*3) = 12 를 만족하는 텐서 크기변경

print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


Squeeze / UnSqueeze

In [26]:
ft1 = torch.FloatTensor([[0],[1],[2]])
print(ft1)
print(ft1.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [27]:
print(ft1.squeeze()) # [3,1]이었던 두번째 차원이 제거되면서 [3,]의 크기를 갖는 텐서(1차원 벡터)로 변경
print(ft1.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [28]:
ft2 = torch.Tensor([0,1,2])
print(ft2.shape)

torch.Size([3])


In [29]:
#Unsqueeze 연산
print(ft2.unsqueeze(0))
print(ft2.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [30]:
#View 연산 (== Unsqueeze)
print(ft2.view(1, -1))
print(ft2.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [33]:
# 타입캐스팅

lt = torch.LongTensor([1,2,3,4])
print(lt)
print(lt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [36]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)
print(bt.long()) # long type tensor
print(bt.float()) # float type tensor

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [37]:
# concatenate
# 딥러닝에서는 주로 모델의 입력 또는 중간 연산에서 두개의 텐서를 연결하는 경우가 많다. 두 텐서를 연결해서 입력으로 사용하는 것은 두가지의 정보를 모두 사용한다는 의미.
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])
print(torch.cat([x,y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [38]:
print(torch.cat([x,y], dim=1)) # 2*2 tensor > 2*4 tensor

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [41]:
# stacking

x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))

print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))
# unsqueeze(0)를 함으로써 3개의 벡터는 전부 (1,2)의 크기의 2차원 텐서로 변경.

print(torch.stack([x,y,z], dim=1)) # 두번째 차원이 증가하도록 

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [42]:
# ones_like, zeros_like : 입력 텐서와 크기를 동일하게 하게 하면서 값을 1/0으로 채우기

x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [43]:
# Inplace Operation
x = torch.FloatTensor([[1,2],[3,4]])

In [44]:
print(x)
print(x.mul(2.))
print(x.mul_(2.)) # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력

tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
