In [13]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [14]:
torch.manual_seed(1)
# 난수 발생 순서와 값을 동일하게 보장.

In [15]:
# 변수선언
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [16]:
print(x_train.shape)
print(y_train.shape)

torch.Size([3, 1])
torch.Size([3, 1])


In [17]:
W = torch.zeros(1, requires_grad=True)
print(W) # 0으로 초기화된 가중치

tensor([0.], requires_grad=True)


requires_grad = True
- 자동미분기능 적용 : 선형회귀부터 신경망과 같은 복잡한 구조에서 파라미터들이 모두 이 기능이 적용
- 계산그래프가 생성되며 backward 함수를 호출하면 그래프로부터 자동으로 미분이 계산됨.

In [18]:
b = torch.zeros(1, requires_grad=True)
print(b) # bias 초기화

tensor([0.], requires_grad=True)


In [19]:
hypothesis = x_train*W+b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [20]:
# 비용함수 선언 : 선형회귀의 비용함수에 해당되는 평균제곱오차 선언
cost = torch.mean((hypothesis - y_train)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [21]:
optimizer = optim.SGD([W,b], lr=0.01)
optimizer.zero_grad()
# 파이토치는 미분을 통해 얻은 기울기를 이전에 계산된 기울기 값에 누적시키므로 미분값을 0으로 초기화 해줘야 함.
cost.backward()
optimizer.step()

In [22]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):
    hypothesis = x_train*W+b
    cost = torch.mean((hypothesis - y_train)**2)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch %100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b:{:.3f}, Cost:{:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()))

Epoch    0/2000 W: 0.353, b:0.151, Cost:14.770963
Epoch  100/2000 W: 1.746, b:0.577, Cost:0.047939
Epoch  200/2000 W: 1.801, b:0.453, Cost:0.029624
Epoch  300/2000 W: 1.843, b:0.356, Cost:0.018306
Epoch  400/2000 W: 1.877, b:0.280, Cost:0.011312
Epoch  500/2000 W: 1.903, b:0.220, Cost:0.006990
Epoch  600/2000 W: 1.924, b:0.173, Cost:0.004319
Epoch  700/2000 W: 1.940, b:0.136, Cost:0.002669
Epoch  800/2000 W: 1.953, b:0.107, Cost:0.001649
Epoch  900/2000 W: 1.963, b:0.084, Cost:0.001019
Epoch 1000/2000 W: 1.971, b:0.066, Cost:0.000630
Epoch 1100/2000 W: 1.977, b:0.052, Cost:0.000389
Epoch 1200/2000 W: 1.982, b:0.041, Cost:0.000240
Epoch 1300/2000 W: 1.986, b:0.032, Cost:0.000149
Epoch 1400/2000 W: 1.989, b:0.025, Cost:0.000092
Epoch 1500/2000 W: 1.991, b:0.020, Cost:0.000057
Epoch 1600/2000 W: 1.993, b:0.016, Cost:0.000035
Epoch 1700/2000 W: 1.995, b:0.012, Cost:0.000022
Epoch 1800/2000 W: 1.996, b:0.010, Cost:0.000013
Epoch 1900/2000 W: 1.997, b:0.008, Cost:0.000008
Epoch 2000/2000 W: 