In [2]:
import numpy as np

In [3]:
x=[1,2,3]
a = np.array(x)
print(a.shape, a.ndim)

(3,) 1


In [5]:
x1 = np.arange(5)
print(x1) #같은내용이지만 출력물이 다르다
x2 = list(range(5))
print(x2)

[0 1 2 3 4]
[0, 1, 2, 3, 4]


In [6]:
x3 = np.arange(10,20,2)
print(x3)

[10 12 14 16 18]


In [10]:
# BroadCasting : 산술연산중에 다른 모양의 배열을 처리할 수 있는 기능을 말함
a1 = np.array([1,2,3,4])
b1 = np.array([[10],[20],[30],[40]])
c2 = a1*b1
print(c2)

[[ 10  20  30  40]
 [ 20  40  60  80]
 [ 30  60  90 120]
 [ 40  80 120 160]]


In [11]:
a3 = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
a4 = np.array([0,1,2])
print(a3 + a4)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
