In [1]:
import numpy as np

In [2]:
arr = np.array([[1., 2., 3.],[4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [7]:
print(arr * arr)
print(arr-arr)

[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
arr2>arr  # 같은크기를 가지는 배열간의 비교연산은 불리언 배열을 반환한다.

array([[False,  True, False],
       [ True, False,  True]])

In [10]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]


In [14]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[2])
print(arr2d[0][2])
print(arr2d[0,2])

[7 8 9]
3
3


In [15]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [20]:
old_values = arr3d[0].copy()
arr3d[0] = 42

arr3d[0] = old_values
print(arr3d)

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]


In [21]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [22]:
x[0]

array([7, 8, 9])

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [29]:
print(arr2d[:2])
print(arr2d[:2, 1:])

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


In [36]:
print(arr2d[1, :2])
print(np.array([4,5]))
print(arr2d[:, :1])
arr2d[:2, 1:]=0
arr2d

[4 0]
[4 5]
[[1]
 [4]
 [7]]


array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## 불리언값으로 선택하기

In [39]:
name=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)
print(name)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.03845958  0.35142658  0.79975512  0.60968637]
 [-0.05339426 -0.08741446  0.95545539  0.74269417]
 [ 1.1027687  -0.7177041   0.41585341  0.12049979]
 [ 2.29180992  2.25843218 -0.71615589  0.36478697]
 [-0.00573607  1.67007823  0.64917454  1.37046453]
 [ 0.20839368  1.66079822 -0.91089519  0.9775112 ]
 [-0.99731823  0.25892468 -0.57214549  0.33695463]]


In [40]:
name=='Bob'

array([ True, False, False,  True, False, False, False])

In [41]:
data[name=='Bob']

array([[ 0.03845958,  0.35142658,  0.79975512,  0.60968637],
       [ 2.29180992,  2.25843218, -0.71615589,  0.36478697]])

In [42]:
data[name=='Bob',2:]

array([[ 0.79975512,  0.60968637],
       [-0.71615589,  0.36478697]])

In [43]:
data[name=='Bob',3]

array([0.60968637, 0.36478697])

In [44]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [46]:
data[~(name == 'Bob')]

array([[-0.05339426, -0.08741446,  0.95545539,  0.74269417],
       [ 1.1027687 , -0.7177041 ,  0.41585341,  0.12049979],
       [-0.00573607,  1.67007823,  0.64917454,  1.37046453],
       [ 0.20839368,  1.66079822, -0.91089519,  0.9775112 ],
       [-0.99731823,  0.25892468, -0.57214549,  0.33695463]])