In [4]:
import numpy as np

In [3]:
# fancy indexing > 정수배열을 사용한 색인 > 슬라이싱과는 달리 선택된 데이터를 새로운 배열로 복사
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [4]:
# 특정한 순서로 row를 선택하고 싶다면 원하는 순서가 명시된 정수가 담긴 ndarray나 리스트를 넘긴다.
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [5]:
#색인으로 음수를 사용하면 끝에서부터 row를 선택한다// 맨 뒤 (-1)
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [7]:
# 다차원 색인배열을 넘길때 > 각각의 색인튜플에 대응하는 1차원 배열이 선택됨
arr = np.arange(32).reshape((8,4))
print(arr)
print(arr[[1,5,7,2],[0,3,1,2]]) #(1,0),(5,3),(7,1),(2,2)에 대응되는 원소들이 선택됨. 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[ 4 23 29 10]


In [10]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [ ]:
## 4.1.7 배열 전치와 축 바꾸기

arr = np.arange(15).reshape((3,5))
print(arr)

In [7]:
# 데이터를 복사하지 않고 데이터의 모양이 바뀐 뷰를 반환하는 기능
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [9]:
# 행렬의 내적 np.dot

arr = np.random.randn(6,3)
print(arr)
print(np.dot(arr.T, arr))

[[ 0.87184467 -1.8850145   1.20735988]
 [-0.25595101  0.20287274  0.77021243]
 [-0.17818    -0.37880889  0.08934756]
 [ 0.87474395  0.22352906  0.64656307]
 [-0.4642704   0.39121813 -0.52272632]
 [-0.66272324 -0.60197561 -1.62704181]]
[[ 2.27729823 -1.21502623  2.72611559]
 [-1.21502623  4.30332466 -1.23401632]
 [ 2.72611559 -1.23401632  5.39747972]]


In [11]:
arr = np.arange(16).reshape((2,2,4))
print(arr)
print(arr.transpose((1,0,2)))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [12]:
print(arr)
print(arr.swapaxes(1,2)) # 데이터를 복사하지 않고 원래 데이터에 대한 뷰를 반환

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]
